console.log("[HelloAgain] Content script loaded on",window.location.href);let c=!0;chrome.storage.sync.get({showHalButton:!0},r=>{c=r.showHalButton});chrome.storage.onChanged.addListener(r=>{r.showHalButton&&(c=r.showHalButton.newValue,document.querySelectorAll(".helloagain-save-wrapper").forEach(o=>{o.style.display=c?"flex":"none"}))});function s(r,o="success"){const t=document.getElementById("helloagain-toast");t&&t.remove();const e=document.createElement("div");e.id="helloagain-toast",e.textContent=r,Object.assign(e.style,{position:"fixed",bottom:"24px",right:"24px",padding:"12px 20px",borderRadius:"12px",background:o==="success"?"rgba(0,212,255,0.95)":"rgba(239,68,68,0.95)",color:o==="success"?"#0a0a0f":"#fff",fontWeight:"600",fontSize:"14px",fontFamily:"'Inter', -apple-system, sans-serif",zIndex:"999999",boxShadow:"0 4px 20px rgba(0,0,0,0.3)",transition:"opacity 0.3s, transform 0.3s",opacity:"0",transform:"translateY(10px)"}),document.body.appendChild(e),requestAnimationFrame(()=>{e.style.opacity="1",e.style.transform="translateY(0)"}),setTimeout(()=>{e.style.opacity="0",e.style.transform="translateY(10px)",setTimeout(()=>e.remove(),300)},2500)}function y(r){var f,h;const o=r.querySelector('[data-testid="tweetText"]'),t=(o==null?void 0:o.textContent)||"",e=r.querySelector('a[role="link"][href^="/"]'),i=((e==null?void 0:e.getAttribute("href"))||"").replace("/","").split("/")[0]||"",a=r.querySelector('[data-testid="User-Name"]'),l=((f=a==null?void 0:a.querySelector("span"))==null?void 0:f.textContent)||"",d=(h=r.querySelector('a[href*="/status/"] time'))==null?void 0:h.parentElement,m=((d==null?void 0:d.getAttribute("href"))||"").match(/\/status\/(\d+)/),b=m?m[1]:"",u=r.querySelector("time"),v=(u==null?void 0:u.getAttribute("datetime"))||"",A=r.querySelectorAll('img[src*="pbs.twimg.com/media"]'),w=Array.from(A).map(x=>x.src);return{content:t,author:i,authorName:l,postId:b,timestamp:v,mediaUrls:w}}function S(r){const o=y(r);if(!o.postId)return null;const t=document.createElement("button");return t.className="helloagain-save-btn",t.title="Save to HAL",t.innerHTML=`
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
    </svg>
  `,Object.assign(t.style,{background:"none",border:"none",color:"#71767b",cursor:"pointer",padding:"8px",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",transition:"all 0.2s"}),t.addEventListener("mouseenter",()=>{t.style.color="#00d4ff",t.style.background="rgba(0,212,255,0.1)"}),t.addEventListener("mouseleave",()=>{t.style.color="#71767b",t.style.background="none"}),t.addEventListener("click",e=>{e.preventDefault(),e.stopPropagation(),t.style.color="#00d4ff";try{chrome.runtime.sendMessage({type:"SAVE_BOOKMARK",data:{postId:o.postId,content:o.content,author:o.author,authorName:o.authorName,timestamp:o.timestamp,mediaUrls:JSON.stringify(o.mediaUrls)}},n=>{if(chrome.runtime.lastError){console.error("[HelloAgain]",chrome.runtime.lastError.message),s("HAL connection lost — reload the page","error");return}n!=null&&n.error?n.status===409?s("Already saved ✓","success"):n.status===401?s("Sign in to Hello Again Links first","error"):s(n.error,"error"):(s("Saved to HAL ✓"),t.innerHTML=`
              <svg width="18" height="18" viewBox="0 0 24 24" fill="#00d4ff" stroke="#00d4ff" stroke-width="2">
                <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
              </svg>
            `)})}catch{s("HAL connection lost — reload the page","error")}}),t}function p(r){r.querySelectorAll('article[data-testid="tweet"]').forEach(t=>{if(t.getAttribute("data-helloagain-enhanced"))return;t.setAttribute("data-helloagain-enhanced","true");const e=t.querySelector('[role="group"]');if(!e)return;const n=S(t);if(n){const a=document.createElement("div");a.className="helloagain-save-wrapper",a.style.display=c?"flex":"none",a.style.alignItems="center",a.appendChild(n),e.appendChild(a)}const i=t.querySelector('[data-testid="bookmark"]');i&&!i.getAttribute("data-hal-mirrored")&&(i.setAttribute("data-hal-mirrored","true"),i.addEventListener("click",()=>{const a=y(t);if(a.postId)try{chrome.runtime.sendMessage({type:"SAVE_BOOKMARK",data:{postId:a.postId,content:a.content,author:a.author,authorName:a.authorName,timestamp:a.timestamp,mediaUrls:JSON.stringify(a.mediaUrls)}},l=>{chrome.runtime.lastError,l&&!l.error&&s("Also saved to HAL ✓")})}catch{}}))})}function g(){p(document.body),new MutationObserver(o=>{for(const t of o)for(const e of t.addedNodes)e instanceof HTMLElement&&p(e)}).observe(document.body,{childList:!0,subtree:!0})}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",g):g();
