console.log("[HelloAgain] Content script loaded on",window.location.href);let l=!0;chrome.storage.sync.get({showHalButton:!0},a=>{l=a.showHalButton});chrome.storage.onChanged.addListener(a=>{a.showHalButton&&(l=a.showHalButton.newValue,document.querySelectorAll(".helloagain-save-wrapper").forEach(o=>{o.style.display=l?"flex":"none"}))});function i(a,o="success"){const t=document.getElementById("helloagain-toast");t&&t.remove();const e=document.createElement("div");e.id="helloagain-toast",e.textContent=a,Object.assign(e.style,{position:"fixed",bottom:"24px",right:"24px",padding:"12px 20px",borderRadius:"12px",background:o==="success"?"rgba(0,212,255,0.95)":"rgba(239,68,68,0.95)",color:o==="success"?"#0a0a0f":"#fff",fontWeight:"600",fontSize:"14px",fontFamily:"'Inter', -apple-system, sans-serif",zIndex:"999999",boxShadow:"0 4px 20px rgba(0,0,0,0.3)",transition:"opacity 0.3s, transform 0.3s",opacity:"0",transform:"translateY(10px)"}),document.body.appendChild(e),requestAnimationFrame(()=>{e.style.opacity="1",e.style.transform="translateY(0)"}),setTimeout(()=>{e.style.opacity="0",e.style.transform="translateY(10px)",setTimeout(()=>e.remove(),300)},2500)}function y(a){var f,h;const o=a.querySelector('[data-testid="tweetText"]'),t=(o==null?void 0:o.textContent)||"",e=a.querySelector('a[role="link"][href^="/"]'),s=((e==null?void 0:e.getAttribute("href"))||"").replace("/","").split("/")[0]||"",n=a.querySelector('[data-testid="User-Name"]'),d=((f=n==null?void 0:n.querySelector("span"))==null?void 0:f.textContent)||"",c=(h=a.querySelector('a[href*="/status/"] time'))==null?void 0:h.parentElement,m=((c==null?void 0:c.getAttribute("href"))||"").match(/\/status\/(\d+)/),b=m?m[1]:"",u=a.querySelector("time"),v=(u==null?void 0:u.getAttribute("datetime"))||"",x=a.querySelectorAll('img[src*="pbs.twimg.com/media"]'),w=Array.from(x).map(A=>A.src);return{content:t,author:s,authorName:d,postId:b,timestamp:v,mediaUrls:w}}function S(a){const o=y(a);if(!o.postId)return null;const t=document.createElement("button");return t.className="helloagain-save-btn",t.title="Save to HAL",t.innerHTML=`
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
    </svg>
  `,Object.assign(t.style,{background:"none",border:"none",color:"#71767b",cursor:"pointer",padding:"8px",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",transition:"all 0.2s"}),t.addEventListener("mouseenter",()=>{t.style.color="#00d4ff",t.style.background="rgba(0,212,255,0.1)"}),t.addEventListener("mouseleave",()=>{t.style.color="#71767b",t.style.background="none"}),t.addEventListener("click",e=>{e.preventDefault(),e.stopPropagation(),t.style.color="#00d4ff",chrome.runtime.sendMessage({type:"SAVE_BOOKMARK",data:{postId:o.postId,content:o.content,author:o.author,authorName:o.authorName,timestamp:o.timestamp,mediaUrls:JSON.stringify(o.mediaUrls)}},r=>{r!=null&&r.error?r.status===409?i("Already saved ✓","success"):r.status===401?i("Sign in to Hello Again Links first","error"):i(r.error,"error"):(i("Saved to HAL ✓"),t.innerHTML=`
            <svg width="18" height="18" viewBox="0 0 24 24" fill="#00d4ff" stroke="#00d4ff" stroke-width="2">
              <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>
            </svg>
          `)})}),t}function p(a){a.querySelectorAll('article[data-testid="tweet"]').forEach(t=>{if(t.getAttribute("data-helloagain-enhanced"))return;t.setAttribute("data-helloagain-enhanced","true");const e=t.querySelector('[role="group"]');if(!e)return;const r=S(t);if(r){const n=document.createElement("div");n.className="helloagain-save-wrapper",n.style.display=l?"flex":"none",n.style.alignItems="center",n.appendChild(r),e.appendChild(n)}const s=t.querySelector('[data-testid="bookmark"]');s&&!s.getAttribute("data-hal-mirrored")&&(s.setAttribute("data-hal-mirrored","true"),s.addEventListener("click",()=>{const n=y(t);n.postId&&chrome.runtime.sendMessage({type:"SAVE_BOOKMARK",data:{postId:n.postId,content:n.content,author:n.author,authorName:n.authorName,timestamp:n.timestamp,mediaUrls:JSON.stringify(n.mediaUrls)}},d=>{d&&!d.error&&i("Also saved to HAL ✓")})}))})}function g(){p(document.body),new MutationObserver(o=>{for(const t of o)for(const e of t.addedNodes)e instanceof HTMLElement&&p(e)}).observe(document.body,{childList:!0,subtree:!0})}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",g):g();
